### ISSUE TITLE
Won't compile with latest 'unliftio'

### ISSUE THREAD

**Issue by tom-audm** [psibi/fb#9]
[The implementation of MonadUnliftIO](https://github.com/psibi/fb/blob/master/src/Facebook/Monad.hs#L89-L98) is broken since https://github.com/fpco/unliftio/commit/d327ae40853635363c3eae8196bb1ee9e88b5c57

```
[ 2 of 17] Compiling Facebook.Monad   ( src/Facebook/Monad.hs, dist/build/Facebook/Monad.o )

src/Facebook/Monad.hs:90:3: error:
    The class method signature for ‘askUnliftIO’
      lacks an accompanying binding
      (The class method signature must be given where ‘askUnliftIO’ is declared)
   |
90 |   askUnliftIO :: FacebookT auth m (UnliftIO (FacebookT auth m))
   |   ^^^^^^^^^^^

src/Facebook/Monad.hs:91:3: error:
    ‘askUnliftIO’ is not a (visible) method of class ‘MonadUnliftIO’
   |
91 |   askUnliftIO =
   |   ^^^^^^^^^^^
```

**Comment by psibi** [comment]
Thanks for the report. I have released a new version which has fixes for that. Thanks!
